force-app/main/default/objects/Category__c/Category__c.object-meta.xml
<CustomObject>
    <description>This is a custom object to do category management which is used on a case.
This is a custom object because the built in category management classification is not easy to apply on cases and is used mainly in the Knowlegde base. 
This Custom object is integrated in different LWC components to track the categories of cases</description>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Category__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Category__c/fields/SubCategory__c.field-meta.xml
<CustomField>
    <fullName>SubCategory__c</fullName>
    <label>SubCategory</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CategoryMappingService.cls
public with sharing class CategoryMappingService {
@AuraEnabled(cacheable=true)
public static Map<String, String> getSubToCategoryMap() {
    Map<String, String> result = new Map<String, String>();

    for (Category__c cat : [
        SELECT Category__c, SubCategory__c
        FROM Category__c
        WHERE Category__c != null AND SubCategory__c != null
    ]) {
        result.put(cat.SubCategory__c, cat.Category__c);
    }

    return result;
}
}